server:
  port: 9002
  servlet:
    context-path: /
    session:
      cookie:
        name: JSESSIONID_OAUTH2_SSO

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

  #DefaultUserAuthenticationConverter
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    #    password: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.crhms.security.authorizationserver: debug
